src/Entity/Smartphone.php
<?php

namespace App\Entity;

use App\Repository\SmartphoneRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SmartphoneRepository::class)]
class Smartphone
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $etat = null;

    #[ORM\Column(length: 255)]
    private ?string $systeme = null;

    #[ORM\Column(length: 255)]
    private ?string $stockage = null;

    #[ORM\Column(length: 255)]
    private ?string $ram = null;

    #[ORM\Column(length: 255)]
    private ?string $taille_ecran = null;

    #[ORM\Column(length: 255)]
    private ?string $reseau = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $photo = null;

    #[ORM\Column(length: 255)]
    private ?string $prix = null;

    #[ORM\ManyToOne(inversedBy: 'smartphone')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Mark $mark = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getEtat(): ?string
    {
        return $this->etat;
    }

    public function setEtat(string $etat): self
    {
        $this->etat = $etat;

        return $this;
    }

    public function getSysteme(): ?string
    {
        return $this->systeme;
    }

    public function setSysteme(string $systeme): self
    {
        $this->systeme = $systeme;

        return $this;
    }

    public function getStockage(): ?string
    {
        return $this->stockage;
    }

    public function setStockage(string $stockage): self
    {
        $this->stockage = $stockage;

        return $this;
    }

    public function getRam(): ?string
    {
        return $this->ram;
    }

    public function setRam(string $ram): self
    {
        $this->ram = $ram;

        return $this;
    }

    public function getTailleEcran(): ?string
    {
        return $this->taille_ecran;
    }

    public function setTailleEcran(string $taille_ecran): self
    {
        $this->taille_ecran = $taille_ecran;

        return $this;
    }

    public function getReseau(): ?string
    {
        return $this->reseau;
    }

    public function setReseau(string $reseau): self
    {
        $this->reseau = $reseau;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getPrix(): ?string
    {
        return $this->prix;
    }

    public function setPrix(string $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getMark(): ?Mark
    {
        return $this->mark;
    }

    public function setMark(?Mark $mark): self
    {
        $this->mark = $mark;

        return $this;
    }
}

src/Form/SmartphoneType.php
<?php

namespace App\Form;

use App\Entity\Mark;
use App\Entity\Smartphone;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Choice;

class SmartphoneType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
{
    $builder
        ->add('name', TextType::class, [
            'label' => 'Nom'
        ])
        ->add('mark', EntityType::class, [
            'class' => Mark::class,
            'choice_label' => 'name', 
        ])
        ->add('etat', ChoiceType::class, [
            'label' => 'État',
            'choices' => [
                'Neuf' => 'neuf',
                'DEEE' => 'DEEE',
                'REPARABLE' => 'REPARABLE',
                'BLOQUE' => 'BLOQUE',
                'RECONDITIONNE' => 'RECONDITIONNE',
                'RECONDITIONABLE	' => 'RECONDITIONABLE'

            
                

                   

            ],
            
        ])
        ->add('systeme', ChoiceType::class, [
            'label' => 'Système d\'exploitation',
            'choices' => [
                'Android' => 'android',
                'IOS' => 'IOS',
                'Windows 10 Mobile ' => 'Windows 10 Mobile ',
                'BlackBerry OS' => 'BlackBerry OS'

            ],
        ])
        ->add('stockage', ChoiceType::class, [
            'label' => 'Capacité de stockage (Go)',
            'choices' => [
                '16 Go' => '16 Go',
                '32 Go' => '32 Go',
                '64 Go' => '64 Go',
                '120 Go' => '120 Go'

            ],
        ])
        ->add('ram', ChoiceType::class, [
            'label' => 'RAM (Go)',
            'choices' => [
                '2 Go' => '2 Go',
                '4 Go' => '4 Go',
                '8 Go' => '8 Go',
                '16 Go' => '16 Go',
                '32 Go' => '32 Go',

            ],
        ])
        ->add('taille_ecran', ChoiceType::class, [
            'label' => 'Taille de l\'écran (pouces)',
            'choices' => [
                "3,5'' " => "3,5'' ",
                "4'' " => "4'' ",
                "5'' " => "5'' ",
                "6'' " => "6'' ",
                "7'' " => "7'' ",



            ],
        ])
        ->add('reseau', ChoiceType::class, [
            'label' => 'Réseau',
            'choices' => [
                '3G' => '3g',
                '4G' => '4g',
                '5G' => '5g'
            ],
            
        ])
        ->add('photo', FileType::class, [
            'label' => 'Photo',
            'required' => false
        ])
    ;
}

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Smartphone::class,
        ]);
    }
}

src/Controller/SmartphoneController.php
<?php

namespace App\Controller;

use App\Entity\Smartphone;
use Symfony\Component\String\Slugger\SluggerInterface;
use App\Form\SmartphoneType;
use App\Repository\SmartphoneRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;



#[Route('/smartphone')]
class SmartphoneController extends AbstractController
{
    #[Route('/', name: 'app_smartphone_index', methods: ['GET'])]
    public function index(SmartphoneRepository $smartphoneRepository): Response
    {
        return $this->render('smartphone/index.html.twig', [
            'smartphones' => $smartphoneRepository->findAll(),
        ]);
    }

    public function calculatePrice($ram, $stockage, $etat)
    {
        
        $ramEnGo = (int)$ram;
        $stockageEnGo = (int)$stockage;
        $prix = $ramEnGo * 30 + $stockageEnGo * 31;
        if($etat === 'DEEE') $prix = ($prix-$prix*0.25);
        if($etat === 'REPARABLE') $prix = ($prix-$prix*0.5);
        if($etat === 'BLOQUE') $prix = ($prix-$prix*0.6);
        if($etat === 'RECONDITIONNE') $prix = ($prix-$prix*0.2);
        if($etat === 'RECONDITIONABLE') $prix = ($prix-$prix*0.6);


        return "$prix euros";
    }

    #[Route('/new', name: 'app_smartphone_new', methods: ['GET', 'POST'])]
    public function new(Request $request, SmartphoneRepository $smartphoneRepository,SluggerInterface $slugger): Response
    {
        $smartphone = new Smartphone();
        $form = $this->createForm(SmartphoneType::class, $smartphone);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
           
            $ram = $form->get('ram')->getData();
            $stockage = $form->get('stockage')->getData();
            $etat = $form->get('etat')->getData();
            $imageFile = $form->get('photo')->getData();

            $prix = $this->calculatePrice($ram, $stockage, $etat);

    
            $smartphone->setPrix($prix);

            
            if ($imageFile) {
                $originalImageName = pathinfo($imageFile->getClientOriginalName(), PATHINFO_FILENAME);
                $safeImageName = 'uploads/images/'. $slugger->slug($originalImageName) . '.' . $imageFile->guessExtension();

                try {
                    $imageFile->move(
                        $this->getParameter('images_directory'),
                        $safeImageName
                    );

                    $smartphone->setPhoto($safeImageName);
                } catch (FileException $e) {
                    die("erreur de chargement de l'image !!");
                }
            }
            $smartphoneRepository->save($smartphone, true);

            return $this->redirectToRoute('app_smartphone_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('smartphone/new.html.twig', [
            'smartphone' => $smartphone,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_smartphone_show', methods: ['GET'])]
    public function show(Smartphone $smartphone): Response
    {
        return $this->render('smartphone/show.html.twig', [
            'smartphone' => $smartphone,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_smartphone_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Smartphone $smartphone, SmartphoneRepository $smartphoneRepository): Response
    {
        $form = $this->createForm(SmartphoneType::class, $smartphone);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $smartphoneRepository->save($smartphone, true);

            return $this->redirectToRoute('app_smartphone_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('smartphone/edit.html.twig', [
            'smartphone' => $smartphone,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_smartphone_delete', methods: ['POST'])]
    public function delete(Request $request, Smartphone $smartphone, SmartphoneRepository $smartphoneRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$smartphone->getId(), $request->request->get('_token'))) {
            $smartphoneRepository->remove($smartphone, true);
        }

        return $this->redirectToRoute('app_smartphone_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/smartphone/_delete_form.html.twig
<form method="post" action="{{ path('app_smartphone_delete', {'id': smartphone.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ smartphone.id) }}">
    <button class="btn btn-primary m-1">Delete</button>
</form>

templates/smartphone/_form.html.twig
{% extends 'base.html.twig' %}

{% block body %}





{{ form_start(form, {'attr': {'class': 'formContact card-body row row-cols-2'}}) }}

<div class="form-group ">

	{{ form_label(form.name, 'Nom', {'label_attr': {'class': 'control-label'}}) }}
	{{ form_widget(form.name, {'attr': {'class': 'form-control'}}) }}
	{{ form_errors(form.name, {'attr': {'class': 'text-danger'}}) }}
</div>

<div class="form-group">
	{{ form_label(form.mark, 'Marque', {'label_attr': {'class': 'control-label'}}) }}
	{{ form_widget(form.mark, {'attr': {'class': 'form-select'}}) }}
	{{ form_errors(form.mark, {'attr': {'class': 'text-danger'}}) }}
</div>

<div class="form-group">
	{{ form_label(form.ram, 'RAM', {'label_attr': {'class': 'control-label'}}) }}
	{{ form_widget(form.ram, {'attr': {'class': 'form-select'}}) }}
	{{ form_errors(form.ram, {'attr': {'class': 'text-danger'}}) }}
</div>

<div class="form-group">
	{{ form_label(form.taille_ecran, 'Taille d\'écran', {'label_attr': {'class': 'control-label'}}) }}
    {{ form_widget(form.taille_ecran, {'attr': {'class': 'form-select'}}) }}
    {{ form_errors(form.taille_ecran, {'attr': {'class': 'text-danger'}}) }}
</div>

<div class="form-group">
	{{ form_label(form.reseau, 'Reseau', {'label_attr': {'class': 'control-label'}}) }}
    {{ form_widget(form.reseau, {'attr': {'class': 'form-select'}}) }}
    {{ form_errors(form.reseau, {'attr': {'class': 'text-danger'}}) }}
</div>

<div class="form-group">
	{{ form_label(form.stockage, 'Stockage', {'label_attr': {'class': 'control-label'}}) }}
    {{ form_widget(form.stockage, {'attr': {'class': 'form-select'}}) }}
    {{ form_errors(form.stockage, {'attr': {'class': 'text-danger'}}) }}
</div>

<div class="form-group">
	{{ form_label(form.systeme, 'Systeme', {'label_attr': {'class': 'control-label'}}) }}
    {{ form_widget(form.systeme, {'attr': {'class': 'form-select'}}) }}
    {{ form_errors(form.systeme, {'attr': {'class': 'text-danger'}}) }}
</div>

<div class="form-group">
	{{ form_label(form.photo, 'Photo', {'label_attr': {'class': 'control-label'}}) }}
    {{ form_widget(form.photo, {'attr': {'class': 'form-control'}}) }}
    {{ form_errors(form.photo, {'attr': {'class': 'text-danger'}}) }}
</div>

<div class="form-group">
	{{ form_label(form.etat, 'Etat', {'label_attr': {'class': 'control-label'}}) }}
	{{ form_widget(form.etat, {'attr': {'class': 'form-select'}}) }}
	{{ form_errors(form.etat, {'attr': {'class': 'text-danger'}}) }}
</div> 	
<button class="btn btn-primary">{{ button_label|default('Save') }}</button>


{{ form_end(form) }}

{% endblock %}

templates/smartphone/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Smartphone{% endblock %}

{% block body %}
    <h1>Edit Smartphone</h1>

    {{ include('smartphone/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_smartphone_index') }}">back to list</a>

    {{ include('smartphone/_delete_form.html.twig') }}
{% endblock %}

templates/smartphone/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Smartphone index{% endblock %}

{% block body %}
    <h1>Smartphone index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Marque</th>
                <th>Etat</th>
                <th>Systeme</th>
                <th>Stockage</th>
                <th>Ram</th>
                <th>Taille_ecran</th>
                <th>Reseau</th>
                <th>Photo</th>
                <th>Prix</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for smartphone in smartphones %}
            <tr>
                <td>{{ smartphone.id }}</td>
                <td>{{ smartphone.name }}</td>
                <td>{{ smartphone.marque }}</td>
                <td>{{ smartphone.etat }}</td>
                <td>{{ smartphone.systeme }}</td>
                <td>{{ smartphone.stockage }}</td>
                <td>{{ smartphone.ram }}</td>
                <td>{{ smartphone.tailleEcran }}</td>
                <td>{{ smartphone.reseau }}</td>
                
               
                <td>
                    <a href="{{ path('app_smartphone_show', {'id': smartphone.id}) }}">show</a>
                    <a href="{{ path('app_smartphone_edit', {'id': smartphone.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="12">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_smartphone_new') }}">Create new</a>
{% endblock %}

templates/smartphone/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Smartphone{% endblock %}

{% block body %}
    <div class="container">
        <h1 class="text-center mb-5">Create new Smartphone</h1>
        <div class="row justify-content-center">
                <div class="card card-new">
                    <div class="card-body row row-cols-2">
                        {{ include('smartphone/_form.html.twig') }}
                        
                    </div>
                    

                </div>
        </div>
        
    </div>
    
{% endblock %}

templates/smartphone/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Smartphone{% endblock %}

{% block body %}
    <h1>Smartphone</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ smartphone.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ smartphone.name }}</td>
            </tr>
            <tr>
                <th>Marque</th>
                <td>{{ smartphone.mark.name }}</td>
            </tr>
            <tr>
                <th>Etat</th>
                <td>{{ smartphone.etat }}</td>
            </tr>
            <tr>
                <th>Systeme</th>
                <td>{{ smartphone.systeme }}</td>
            </tr>
            <tr>
                <th>Stockage</th>
                <td>{{ smartphone.stockage }}</td>
            </tr>
            <tr>
                <th>Ram</th>
                <td>{{ smartphone.ram }}</td>
            </tr>
            <tr>
                <th>Taille_ecran</th>
                <td>{{ smartphone.tailleEcran }}</td>
            </tr>
            <tr>
                <th>Reseau</th>
                <td>{{ smartphone.reseau }}</td>
            </tr>
            {# <tr>
                <th>Photo</th>
                <td>
                    <img class="img-thumbnail " src="{{ asset(public/build/images/Logo.png)}} " alt="{{ smartphone.name }}">
 
                </td>
            </tr> #}
            <tr>
                <th>Prix</th>
                <td>{{ smartphone.prix }}</td>
            </tr>
        </tbody>
    </table>

    <a class="btn btn-primary m-1" href="{{ path('app_smartphone_index') }}">back to list</a>

    <a class="btn btn-primary m-1" href="{{ path('app_smartphone_edit', {'id': smartphone.id}) }}">edit</a>

    {{ include('smartphone/_delete_form.html.twig') }}
{% endblock %}